name: Validate ms-common Pull Request

on:
  pull_request:
    paths:
      - "packages/ms-common/**"

env:
  PACKAGE_NAME: ms-common
  PACKAGE_FOLDER: packages/ms-common
  NODE_VERSION: v22.12.0

jobs:
  test:
    runs-on: ubuntu-latest

    name: Validate and Test Changes for ${{ env.PACKAGE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack for Dependency Management
        run: corepack enable

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install Project Dependencies
        run: pnpm install

      - name: Lint Codebase
        working-directory: ${{ env.PACKAGE_FOLDER }}
        run: pnpm lint

      - name: Compile TypeScript Files
        working-directory: ${{ env.PACKAGE_FOLDER }}
        run: pnpm build

      - name: Execute Unit Tests
        working-directory: ${{ env.PACKAGE_FOLDER }}
        run: pnpm test
