name: tests-payments
# tricket on events
on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # take all the code in the project
      - uses: actions/checkout@v2
      - run: cd payments && npm i && npm run test:ci
