# This is a basic workflow that is manually triggered
name: deploy-expiration
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # build out image
      - run: cd expiration && docker build -t sergway/expiration .
      # log into docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # push to docker hub
      - run: docker push sergway/expiration
      # expiration and install doctl
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # get connection credentials to the kuberneties digital ocean cluster
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # telling the deployment to restart it self
      - run: kubectl rollout restart deployment expiration-depl
