name: Publish ms-common Package

on:
  push:
    branches:
      - master
    # paths:
    #   - "packages/ms-common/**"

env:
  PACKAGE_NAME: ms-common
  PACKAGE_FOLDER: packages/ms-common
  NODE_VERSION: v22.12.0
  RUNNER_TOOL_CACHE: /toolcache
  PNPM_CACHE_FOLDER: .cache/pnpm

jobs:
  publish:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    name: Publish Package

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
          run_install: false

      - name: Setup pnpm config
        run: pnpm config set store-dir "$PNPM_CACHE_FOLDER"
      # Makes sure the pnpm store path exists (which is exactly what setup-node cares about)
      - name: Verify PNPM Cache Directory
        run: |
          PNPM_STORE_PATH="$( pnpm store path --silent )"
          if [ ! -d "$PNPM_STORE_PATH" ]; then
            echo "PNPM store directory does not exist, creating it."
            mkdir -p "$PNPM_STORE_PATH"
          else
            echo "PNPM store directory exists."
          fi

      # - name: Enable Corepack for Dependency Management
      #   run: corepack enable

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      # - name: Bump Version and Commit Changes
      #   working-directory: ${{ env.PACKAGE_FOLDER }}
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   run: |
      #     pnpm version patch
      #     git config user.name "GitHub Actions"
      #     git config user.email "actions@github.com"
      #     git commit -am "chore: bump version to patch"
      #     git push origin HEAD:master
