name: Publish ms-common Package

on:
  push:
    branches:
      - master
    paths:
      - "packages/ms-common/**"
  workflow_dispatch: {}

env:
  PACKAGE_NAME: ms-common
  PACKAGE_FOLDER: packages/ms-common
  NODE_VERSION: v22.12.0

jobs:
  publish:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    name: Publish Package

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Bump Version and Commit Changes
        working-directory: ${{ env.PACKAGE_FOLDER }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          pnpm version patch
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "chore: bump version to patch"
          git push origin HEAD:master

      - name: Restore node modules cache if preset
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: "**/node_modules"

      - name: Install Project Dependencies
        run: pnpm install

      - name: Compile TypeScript Files
        working-directory: ${{ env.PACKAGE_FOLDER }}
        run: pnpm build

      - name: Publish to NPM
        run: pnpm publish
        working-directory: ${{ env.PACKAGE_FOLDER }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
