name: Packages PR tests

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        packages:
          - name: ms-common
            folder: packages/ms-common
            node-version: v22.12.0

    steps:
      - name: Checkout code for ${{ matrix.package.name }}
        uses: actions/checkout@v4

      - name: Enable Corepack for ${{ matrix.package.name }}
        run: corepack enable

      - name: Setup Node.js for ${{ matrix.package.name }}
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install dependencies for ${{ matrix.package.name }}
        run: pnpm install

      - name: Run tests ${{ matrix.package.name }}
        working-directory: ${{ matrix.packages.folder }}
        run: pnpm test
