name: Validate Pull Request

on:
  pull_request:
    paths:
      - "packages/**"
      - "services/**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_folders: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ms-common:
              - "packages/ms-common/**"
            ms-auth:
              - "services/ms-auth/**"

  test:
    needs: detect-changes
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

      matrix:
        workspaces:
          - name: ms-common
            type: package
            folder: packages/ms-common
            node-version: v22.12.0

          - name: ms-auth
            type: service
            folder: services/ms-auth
            node-version: v22.12.0

    name: Run Tests for ${{ matrix.workspaces.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process ms-common Changes
        if: contains(needs.detect-changes.outputs.changed_folders, matrix.workspaces.name)
        run: |
          echo "ms-common folder has changes."
          # Add your backend processing commands here

        
      - name: Enable Corepack
        run: corepack enable
        if: contains(needs.detect-changes.outputs.changed_folders, matrix.workspaces.name)


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.workspaces.node-version }}
          cache: "pnpm"
        if: contains(needs.detect-changes.outputs.changed_folders, matrix.workspaces.name)

      - name: Install dependencies
        run: pnpm install
        if: contains(needs.detect-changes.outputs.changed_folders, matrix.workspaces.name)

      - name: Run Lint
        working-directory: ${{ matrix.workspaces.folder }}
        run: pnpm lint
        if: contains(needs.detect-changes.outputs.changed_folders, matrix.workspaces.name)
      
      - name: Build TypeScript
        working-directory: ${{ matrix.workspaces.folder }}
        run: pnpm build
        if: contains(needs.detect-changes.outputs.changed_folders, matrix.workspaces.name)
      
      - name: Run tests
        working-directory: ${{ matrix.workspaces.folder }}
        run: pnpm test
        if: contains(needs.detect-changes.outputs.changed_folders, matrix.workspaces.name)
