name: Validate Pull Request

on:
  pull_request:
    paths:
      - "packages/**"
      - "services/**"

jobs:
  filter-paths:
    runs-on: ubuntu-latest
    outputs:
      ms_common_folder: ${{ steps.changes.outputs.ms_common }}
      ms_auth_folder: ${{ steps.changes.outputs.ms_auth }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter Paths
        id: changes
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            ms_common:
              - "packages/ms-common/**"
            ms_auth:
              - "services/ms-auth/**"
  test:
    needs: filter-paths
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

      matrix:
        workspaces:
          - name: ms-common
            type: package
            folder: packages/ms-common
            node-version: v22.12.0
            enabled: ${{ needs.filter-paths.outputs.ms_common }}

          - name: ms-auth
            type: service
            folder: services/ms-auth
            node-version: v22.12.0
            enabled: ${{ needs.filter-paths.outputs.ms_auth }}

        exclude:
          - workspaces:
              enabled: "false"

    name: Run Tests for ${{ matrix.workspaces.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test
        run: echo ${{ matrix.workspaces.enabled }}

      - name: Enable Corepack
        run: corepack enable
        if: ${{ matrix.workspaces.enabled == 'true' }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.workspaces.node-version }}
          cache: "pnpm"
        if: ${{ matrix.workspaces.enabled == 'true' }}

      - name: Install dependencies
        run: pnpm install
        if: ${{ matrix.workspaces.enabled == 'true' }}

      - name: Run Lint
        working-directory: ${{ matrix.workspaces.folder }}
        run: pnpm lint
        if: ${{ matrix.workspaces.enabled == 'true' }}

      - name: Build TypeScript
        working-directory: ${{ matrix.workspaces.folder }}
        run: pnpm build
        if: ${{ matrix.workspaces.enabled == 'true' }}

      - name: Run tests
        working-directory: ${{ matrix.workspaces.folder }}
        run: pnpm test
        if: ${{ matrix.workspaces.enabled == 'true' }}
