name: Validate Pull Request

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

      matrix:
        workspaces:
          - name: ms-common
            type: package
            folder: packages/ms-common
            node-version: v22.12.0

          - name: ms-auth
            type: service
            folder: services/ms-auth
            node-version: v22.12.0


    name: Run Tests for ${{ matrix.workspaces.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.workspaces.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        working-directory: ${{ matrix.workspaces.folder }}
        run: pnpm lint

      - name: Build TypeScript
        working-directory: ${{ matrix.workspaces.folder }}
        run: pnpm build

      - name: Run tests
        working-directory: ${{ matrix.workspaces.folder }}
        run: pnpm test
