name: Validate ms-common Pull Request

on: ["pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    name: Run Tests for ${{ env.PACKAGE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Build TypeScript
        run: pnpm build

      - name: Run tests
        run: pnpm test
