name: tests-orders
# tricket on events
on:
  pull_request:
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # take all the code in the project
      - uses: actions/checkout@v2
      - run: cd orders && npm i && npm run test:ci
